CREATE TABLE REGION(
REGIONKEY char(10) PRIMARY KEY,
NAME char(10),
COMMENT char(10)
);
CREATE TABLE NATION(
NATIONKEY char(10) PRIMARY KEY,
NAME char(10),
REGIONKEY char(10),
FOREIGN KEY(REGIONKEY) REFERENCES REGION(REGIONKEY),
COMMENT char(10)
);
CREATE TABLE SUPPLIER(
SUPPKEY char(10) PRIMARY KEY,
NAME char(10),
ADDRESS char(10),
NATIONKEY char(10),
FOREIGN KEY(NATIONKEY) REFERENCES NATION(NATIONKEY),
PHONE int,
ACCTBAL int,
COMMENT char(10)
);
CREATE TABLE PART(
PARTKEY char(10) PRIMARY KEY,
NAME char(10),
MFGR char(10),
BRAND char(10),
TYPE char(10),
SIZE float,
CONTAINER char(10),
RETAILPRICE float,
COMMENT char(10),
);
CREATE TABLE PARTSUPP(
PARTKEY char(10),
FOREIGN KEY(PARTKEY) REFERENCES PART(PARTKEY),
SUPPKEY char(10),
FOREIGN KEY(SUPPKEY) REFERENCES SUPPLIER(SUPPKEY),
PRIMARY KEY(PARTKEY,SUPPKEY),
AVAILQTY int,
SUPPLYCOST float,
COMMENT char(10)
);
CREATE TABLE CUSTOMER(                                                   
CUSTKEY char(10) PRIMARY KEY,
NAME char(10),
ADDRESS char(10),
NATIONKEY char(10),
FOREIGN KEY (NATIONKEY) REFERENCES NATION(NATIONKEY),
PHONE int,
ACCTBAL int,
MKTSEGMENT char(10),
COMMENT char(10),
);
CREATE TABLE ORDERS(
ORDERKEY char(10) PRIMARY KEY,
CUSTKEY char(10),
FOREIGN KEY(CUSTKEY) REFERENCES CUSTOMER(CUSTKEY),
ORDERSTATUS char(10),
TOTALPRICE float,
ORDERDATE char(10),
ORDER_PRIORITY int,
CLERK char(10),
SHIP_PRIORITY int,
COMMENT char(10)
);
CREATE TABLE LINEITEM(
ORDERKEY char(10) ,
FOREIGN KEY (ORDERKEY) REFERENCES ORDERS(ORDERKEY),
PARTKEY char(10),
SUPPKEY char(10),
FOREIGN KEY (PARTKEY,SUPPKEY) REFERENCES PARTSUPP(PARTKEY,SUPPKEY),
LINENUMBER int,
PRIMARY KEY(ORDERKEY,LINENUMBER),
QUANTITY int,
EXTENDEDPRICE float,
DISCOUNT float CHECK(DISCOUNT >= 0 AND DISCOUNT <= 0.1),
TAX float CHECK(TAX >= 0 AND TAX <= 0.08),
RETURNFLAG char(1),
LINESTATUS char(1),
SHIPDATE date,
COMMITDATE date,
RECEIPTDATE date,
SHIPINSTRUCT char(10),
SHIPMODE char(10),
COMMENT char(10)
);
