CREATE TABLE CUSTBUY
(
CB_NAME CHAR(255),
CB_QUANTITY CHAR(255),
CB_TOTALPRICE CHAR(255)
);
INSERT
INTO CUSTBUY(CB_NAME,CB_QUANTITY,CB_TOTALPRICE)
SELECT C_NAME,L_QUANTITY,L_EXTENDEDPRICE
FROM CUSTOMER,LINEITEM,ORDERS
WHERE C_CUSTKEY=O_CUSTKEY AND O_ORDERKEY=L_ORDERKEY