CREATE VIEW V_CustAvgOrder(C_CUSTKEY,C_NAME,AVG_PRICE,AVG_QUAITITY)
AS 
SELECT C_CUSTKEY,C_NAME,AVG(L_EXTENDEDPRICE),AVG(L_QUANTITY)
FROM LINEITEM,ORDERS,CUSTOMER
WHERE L_ORDERKEY=O_ORDERKEY AND O_CUSTKEY=C_CUSTKEY
GROUP BY C_CUSTKEY,C_NAME
