SELECT*FROM CUSTOMER C
WHERE C.C_CUSTKEY IN 
(SELECT O.O_CUSTKEY FROM ORDERS O
GROUP BY O.O_CUSTKEY 
HAVING AVG(O.O_TOTALPRICE)>10000 AND C.C_NATIONKEY=
(SELECT N_NATIONKEY FROM NATION
WHERE N_NAME='ÖÐ¹ú')
)