SELECT* FROM CUSTOMER
WHERE C_CUSTKEY IN (
SELECT O_CUSTKEY FROM ORDERS,CUSTOMER
WHERE O_CUSTKEY=C_CUSTKEY  AND C_NATIONKEY=(SELECT N_NATIONKEY FROM NATION WHERE N_NAME='ÖÐ¹ú')
GROUP BY O_CUSTKEY
HAVING(AVG(O_TOTALPRICE)>1000)
)