/*查询至少购买过顾客“张三”购买过的全部零件的顾客姓名。*/
SELECT DISTINCT C1.C_NAME FROM CUSTOMER C1
WHERE NOT EXISTS
(
SELECT * FROM CUSTOMER C2
WHERE C2.C_NAME='张三'AND NOT EXISTS
(
SELECT * FROM CUSTOMER C3
WHERE C1.C_CUSTKEY=C2.C_CUSTKEY AND C2.C_CUSTKEY=C3.C_CUSTKEY
)
)