SELECT AVG(L_EXTENDEDPRICE)AS'平均订单金额',C_NAME,C_CUSTKEY FROM LINEITEM,CUSTOMER,ORDERS
WHERE(CUSTOMER.C_CUSTKEY=ORDERS.O_CUSTKEY AND LINEITEM.L_ORDERKEY=ORDERS.O_ORDERKEY)
GROUP BY C_NAME,C_CUSTKEY
HAVING(AVG(L_EXTENDEDPRICE)>1000)