/*查询没有购买过“海大”制造的“船舶模拟驾驶舱”的顾客*/
SELECT * FROM CUSTOMER C
WHERE NOT EXISTS
(
SELECT* FROM PART P,LINEITEM L,ORDERS O
WHERE P.P_NAME='船舶模拟驾驶舱' AND P.P_MFGR='海大'  AND P.P_PARTKEY=L.L_PARTKEY AND O.O_ORDERKEY=L.L_ORDERKEY AND C.C_CUSTKEY=O.O_CUSTKEY
)