/*查询至少购买过顾客“张三”购买过的全部零件的顾客姓名。*/
SELECT DISTINCT C_NAME FROM CUSTOMER C1
WHERE NOT EXISTS
(
SELECT *FROM CUSTOMER C2,LINEITEM L2,ORDERS O2
WHERE C2.C_NAME='张三' AND O2.O_CUSTKEY=C2.C_CUSTKEY AND L2.L_ORDERKEY=O2.O_ORDERKEY
AND NOT EXISTS 
(
SELECT *FROM LINEITEM L3,ORDERS O3
WHERE(C1.C_CUSTKEY=O3.O_CUSTKEY AND L3.L_PARTKEY=L2.L_PARTKEY AND L3.L_ORDERKEY=O3.O_ORDERKEY)
)
)