/*查询顾客“张三”和“李四”都订购过的全部零件的信息。
查询顾客“张三”和“李四”订购的全部零件的信息。
顾客“张三”订购过，而“李四”没订购过的零件的信息。*/
SELECT *FROM PART WHERE P_PARTKEY IN (SELECT L_PARTKEY FROM LINEITEM,ORDERS,CUSTOMER WHERE C_NAME='张三'AND L_ORDERKEY=O_ORDERKEY AND O_CUSTKEY=C_CUSTKEY )
INTERSECT
SELECT *FROM PART WHERE P_PARTKEY IN (SELECT L_PARTKEY FROM LINEITEM,ORDERS,CUSTOMER WHERE C_NAME='李四'AND L_ORDERKEY=O_ORDERKEY AND O_CUSTKEY=C_CUSTKEY );
SELECT *FROM PART WHERE P_PARTKEY IN (SELECT L_PARTKEY FROM LINEITEM,ORDERS,CUSTOMER WHERE C_NAME='张三'AND L_ORDERKEY=O_ORDERKEY AND O_CUSTKEY=C_CUSTKEY )
UNION
SELECT *FROM PART WHERE P_PARTKEY IN (SELECT L_PARTKEY FROM LINEITEM,ORDERS,CUSTOMER WHERE C_NAME='李四'AND L_ORDERKEY=O_ORDERKEY AND O_CUSTKEY=C_CUSTKEY );
SELECT *FROM PART WHERE P_PARTKEY IN (SELECT L_PARTKEY FROM LINEITEM,ORDERS,CUSTOMER WHERE C_NAME='张三'AND L_ORDERKEY=O_ORDERKEY AND O_CUSTKEY=C_CUSTKEY )
EXCEPT
SELECT *FROM PART WHERE P_PARTKEY IN (SELECT L_PARTKEY FROM LINEITEM,ORDERS,CUSTOMER WHERE C_NAME='李四'AND L_ORDERKEY=O_ORDERKEY AND O_CUSTKEY=C_CUSTKEY );